server:
  port: 9192
  
spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  config: 
    import: optional:configserver:http://localhost:9196

logging.file.name: C:/Users/VenkataprasadKoppara/Documents/codebase/log/microservice.log

#spring.cloud.config.enabled: true
###########################Comment the below details BCZ we are readong the alues from config server#################
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

#logging.level.org.springframework.web: DEBUG

#logging:
#  level:
#   ROOT: DEBUG